version: '3'
services:
  redis:
    image: redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
  dashboard:
    build: 
      context: ./dashboard
    restart: always
    environment:
      - REDIS=redis://redis/
    ports:
      - 80:3000
    links:
      - redis
