version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
  website:
    build: .
    environment:
      - REDIS=redis://redis/
    ports:
      - 8080:3000
    links:
      - redis
