version: '3'
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
  website:
    build: .
    restart: always
    environment:
      - REDIS=redis://redis/
    ports:
      - 80:3000
    links:
      - redis

